### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 1 - Python

### ISSUE THREAD

**Issue by errbufferoverfl** [microsoft/Seasons-of-Serverless#11]
Please provide the following information for your submission:

### What is your name? (First, Last)
Rebecca Trapani

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/errbufferoverfl/violet-lobster

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
Python 3.8, Australia.

Demo link: https://turkey-maker.azurewebsites.net/api/turkey-maker?weight=12

Has basic error handling in that it prints "Pass the weight of your turkey in pounds in the query string or in the request body for your brine equation." if you specify a parameter that is not weight or if you specify a weight that is not a number.

**Main Challenges Faced:**
* Not knowing if it's okay to just round up ingredient weights because I've never cooked a turkey before. Please, no one make a turkey from this.
* Using Azure Functions with PyCharm, I ended up downloading VSCode to follow the [quickstart guide](https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python)

**Comment by jlooper** [comment]
love it!! emojis FTW!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
