### ISSUE TITLE
Challenge 1 Solution - Python

### ISSUE THREAD

**Issue by matt-manuel** [microsoft/Seasons-of-Serverless#12]
What is your name? (First, Last)
Matt Manuel

Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/matt-manuel/seasons-of-serverless

What Challenge is this for? (Challenge number between 1 and 7)
1

(Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

Done in Python. Located near Vancouver, BC.
Ran into a challenge setting up a free tier function using Python. "x64 not supported error" Changed to Basic tier and it worked.

Note: No input sanitizing yet. Will crash on non-numeric input, for example. :-|

Sample call:
https://sos-mamanuel.azurewebsites.net/api/PerfectTurkey?weight=10.1

**Comment by jlooper** [comment]
looks great! yum!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
