### ISSUE TITLE
[CHALLENGE SUBMISSION] - Week 1 Solution in TypeScript

### ISSUE THREAD

**Issue by lechnerc77** [microsoft/Seasons-of-Serverless#13]
Please provide the following information for your submission:

### What is your name? (First, Last)
Christian Lechner

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/lechnerc77/SeasonOfServerlessWeek1

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
The function is implemented in TypeScript.  It provides a GET endpoint. Based on the input handed over via the request body the recipe is determined and returned to the caller. The units need not be lb, they will be converted in the API.
In addition metadata endpoints are provided for the valid values of the recipe type (currently only "turkey") and the available units.
Internally the main mechanics for determining the recipe are handled via a class factory allow to hook in other recipes afterwards

**Comment by jlooper** [comment]
Looking very nice! Well done! The solution, not the turkey, fwiw :) We don't overcook poultry around here

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
