### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 1 - Node.js

### ISSUE THREAD

**Issue by MatsAnd** [microsoft/Seasons-of-Serverless#14]
Please provide the following information for your submission:

### What is your name? (First, Last)
Mats Andreassen

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/MatsAnd/seasons-of-serverless/tree/main/01

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
Great challenge, can't wait to get the next one! 🙌🏼

Example call: https://ma-func-sos-01.azurewebsites.net/api/turkey/8

**Comment by jlooper** [comment]
looks fab! nice one!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
