### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by antempus** [microsoft/Seasons-of-Serverless#15]
Please provide the following information for your submission:

### What is your name? (First, Last)
Robert Steele
### Where is your GitHub Repo ?(Link to your challenge solution)
[challenge one](https://github.com/antempus/SeasonsOfServerlessSolutions/tree/primary/challenge_one
)
### What Challenge is this for? (Challenge number between 1 and 7)
1

**Comment by jlooper** [comment]
hi, can you give me details how to run/test this solution? thanks!

**Comment by Christophe-Ch** [comment]
His solution is under another directory of the repository: https://github.com/antempus/SeasonsOfServerlessSolutions/blob/primary/lib/turkey.ts

If you want to launch it, I believe that opening the folder given in the issue on VS Code then pressing F5 should work (haven’t tried) :)

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉

**Comment by antempus** [comment]
Thanks @Christophe-Ch for responding, that should've been the way to run/validate. 

@jansche Thanks! 🥳
