### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge 1, Powershell

### ISSUE THREAD

**Issue by bjompen** [microsoft/Seasons-of-Serverless#16]
Please provide the following information for your submission:

### What is your name? (First, Last)

Björn Sundling

### Where is your GitHub Repo ?(Link to your challenge solution)

[challenge 1](https://github.com/bjompen/Seasons-of-Serverless/tree/master/challenge_1)

### What Challenge is this for? (Challenge number between 1 and 7)

1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

Solved in pwsh. 

As I have been doing some work in Azure functions before I decided to take the chance to brush up on other skills at the same time, so included is also scripts for deploying the Azure function environment using PowerShell and ARM templates.

As a European I also added a query flag 'realmeasurements' for outputting proper measurements (decilitres and litres) instead of cups and gallons.

If no query input is given it defaults to 10Lbs.

Example 1
> https://\<website\>.azurewebsites.net/api/TurkeyTrigger?weight=12&realmeasurements=true

output:
```
5.44 Kilos of bird
1.4 DL Salt 
30.0 Litres Water
3.7 DL Brown sugar 
3 Shallots
5 Cloves of garlic
1.6 tablespoons of Whole peppercorns
1.6 tablespoons of Dried juniper berries
1.6 tablespoons of Fresh rosemary
0.7 tablespoons of Thyme
Brine for 29 hours and 0 minutes.  
Roast for 3 hours and 0 minutes.
```

Example 2
> https://\<website\>.azurewebsites.net/api/TurkeyTrigger?weight=16

output:
```
16 Lbs of bird
0.8 Cups Salt 
10.6 Gallons Water
2.1 Cups Brown sugar 
4 Shallots
7 Cloves of garlic
2.1 tablespoons of Whole peppercorns
2.1 tablespoons of Dried juniper berries
2.1 tablespoons of Fresh rosemary
1.0 tablespoons of Thyme
Brine for 38 hours and 0 minutes.  
Roast for 4 hours and 0 minutes.
```

**Comment by jlooper** [comment]
:) you could differentiate 'imperial' vs 'metric' as measures, that would be nice :)

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
