### ISSUE TITLE
[CHALLENGE SUBMISSION] Week 1 - Java

### ISSUE THREAD

**Issue by amourany** [microsoft/Seasons-of-Serverless#17]
Please provide the following information for your submission:

### What is your name? (First, Last)
Alexandre Mourany

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/amourany/seasons-of-serverless/tree/master/w1-perfect-turkey

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

My solution is done using **Java 11** and the function is deployed with **GitHub actions**.

#### Demo
Function can be found here : https://perfect-turkey-amou.azurewebsites.net/api/turkey-recipe?weight=5

**Comment by jlooper** [comment]
a delicious solution! nice!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
