### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 01 - PowerShell

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/Seasons-of-Serverless#18]
Please provide the following information for your submission:

### What is your name? (First, Last)
Barbara Forbes

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/Ba4bes/SeasonsOfServerless/tree/main/C01-The_Perfect_Turkey

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

PowerShell, a Function App and Ascii art! All other info is in the readme ;)

**Comment by jlooper** [comment]
Welcome back, Barbara!

**Comment by jlooper** [comment]
sooooo cool!!!!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
