### ISSUE TITLE
Links to file issues in Readme don't work

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/Seasons-of-Serverless#19]
**Describe the bug**
 
Small bug:

In the Readme, under "Submit your solution as a tagged ISSUE to our repository", there are two links to submit an issue (one for a challenge, one for a regular bug). Both links are broken right now.

Both links start with : https://github.com/microsoft/Seasons-of-Serverless/blob/main/issues/
Think this should be https://github.com/microsoft/Seasons-of-Serverless/issues/

🐛

**Comment by jlooper** [comment]
Ah thanks, will fix
