### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge One (C#, Azure Functions, Blazor, Static Web App)

### ISSUE THREAD

**Issue by stuartleaver** [microsoft/Seasons-of-Serverless#20]
Please provide the following information for your submission:

### What is your name? (First, Last)

Stuart Leaver

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/stuartleaver/seasons-of-serverless/tree/main/01-the-perfect-turkey

### What Challenge is this for? (Challenge number between 1 and 7)

1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

C#, an Azure Function, Blazor and a Static Web App. Try it out at [http://www.theperfectturkey.cloud](http://www.theperfectturkey.cloud)

**Comment by jlooper** [comment]
Wowza! Welcome back, Stuart!!

**Comment by stuartleaver** [comment]
Thank you @jlooper. It is good to be back.

**Comment by jlooper** [comment]
love it! thanks for your submission! A+

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
hanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
