### ISSUE TITLE
[CHALLENGE SUBMISSION] Pass! The Cranberry Sauce! 

### ISSUE THREAD

**Issue by MetzinAround** [microsoft/Seasons-of-Serverless#21]
Please provide the following information for your submission:

### What is your name?
Philip Metz

### Where is your GitHub Repo ?
https://github.com/MetzinAround/PerfectTurkey

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
I'm a self taught C# coder looking for an opportunity for his first job. I made this in ASP.NET core using a C# class to hold the recipe logic. I have no idea what I'm doing and hope this works. 

Note: not formatted for mobile.

**Comment by jlooper** [comment]
Awesome! Can you give us a little detail in the README on how to run this? Thanks!!

**Comment by MetzinAround** [comment]
So, it's funny that I put in as much time as I did making a webapp, and only just now realized I am submitting it to a serverless competition. 

Sorry for that. Readme updated to include the URL for the webapp. 

I'll be doing better for the next challenge (I hope).

**Comment by jlooper** [comment]
Awesome!! 🦃🦃🦃🍽🍽🍽🙏🙏🙏

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
