### ISSUE TITLE
[CHALLENGE SUBMISSION] JavaScript

### ISSUE THREAD

**Issue by LocksleyLK** [microsoft/Seasons-of-Serverless#22]
### What is your name? (First, Last)
Locksley Kolakowski

### Where is your GitHub Repo? (Link to your challenge solution)
[GitHub repo](https://github.com/LocksleyLK/seasons-of-serverless/blob/master/challenge-1/README.md)

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
I used JavaScript for my solution!

**Comment by jlooper** [comment]
bravo!

**Comment by LocksleyLK** [comment]
Thank you! I'm looking forward to tomorrow's challenge!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
