### ISSUE TITLE
PowerShell Solution Manbearpiet

### ISSUE THREAD

**Issue by Manbearpiet** [microsoft/Seasons-of-Serverless#25]
What is your name? (First, Last)

Christian Piet

Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/Manbearpiet/seasonofserverless
https://deliciousturkeyrecipeshoppinglist.azurewebsites.net/api/DeliciousTurkeyRecipe?

What Challenge is this for? (Challenge number between 1 and 7)

Challenge 1

(Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

Hi, I hope everyone had a nice Thanksgiving 🦃.

My solution in PowerShell is published at:
https://github.com/Manbearpiet/seasonofserverless

I've published it as a function at:
https://deliciousturkeyrecipeshoppinglist.azurewebsites.net/api/DeliciousTurkeyRecipe?

The function uses a HTTP query string with the keyword Weight (in pounds):
https://deliciousturkeyrecipeshoppinglist.azurewebsites.net/api/DeliciousTurkeyRecipe?Weight=5

It also works with PowerShell:
```ps
$param = @{
URI = 'https://deliciousturkeyrecipeshoppinglist.azurewebsites.net/api/DeliciousTurkeyRecipe'
Body = (@{Weight=5}| ConvertTo-Json)
Method = 'Post'
ContentType = 'application/json'
}
Invoke-Restmethod @param
```

I wanted to create something with more flair, as a nice output (better timeduration output), ASCII art and prettier output.
But I got sucked in, in coding the same solution in C# (my first C# lines ever :-)). I couldn't finish that nor make this a bit more shiney. But still i'm happy with my first function ever yeey!

The function parses the parameterstring or query string to an integer and multiplies the parsed integer in a hashtable with the ingredients as a weight factor and outputs a JSON body with the multiplied values.

**Comment by jlooper** [comment]
Lovely! Thank you for your submission!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
