### ISSUE TITLE
[CHALLENGE SUBMISSION] Week 1

### ISSUE THREAD

**Issue by silvestrijonathan** [microsoft/Seasons-of-Serverless#26]
Please provide the following information for your submission:

### What is your name? (First, Last)

Jonathan Silvestri

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/silvestrijonathan/azure-practice/tree/main/PerfectTurkey

### What Challenge is this for? (Challenge number between 1 and 7)

Challenge 1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

- Followed this tutorial, but used TypeScript to solve the problem: https://docs.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-csharp?WT.mc_id=academic-10922-cxa
- Changed the return of the API call to html so I can apply some basic markup.
- Chose to round all measurements to the nearest quarter or whole number, where appropriate.

You can navigate here to see the code in action: https://perfect-turkey.azurewebsites.net/api/PerfectTurkey. Append a query string `turkeySize` with your turkey's size in numerical form. e.g. `?turkeySize=24`

**Comment by jlooper** [comment]
Terrific job! Love it!

**Comment by silvestrijonathan** [comment]
ty @jlooper! I probably should have used some document methods to make all the elements but I figured a direct approach with all of that would have been fine for this :D

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
