### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by PaulusTM** [microsoft/Seasons-of-Serverless#27]
Please provide the following information for your submission:

### What is your name? (First, Last)

Daniel Paulus

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/PaulusTM/Seasons-of-Serverless/tree/main/src/challenge-1

### What Challenge is this for? (Challenge number between 1 and 7)

1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

Typescript

**Comment by PaulusTM** [comment]
Actual footage from me working on this solution :)

![EoBUKldW8AY3FKv](https://user-images.githubusercontent.com/85584/100555269-9751b980-329a-11eb-9b7b-1a4d5849f4af.jpeg)

**Comment by jansche** [comment]
The code looks reasonable to me, @PaulusTM. Is there somewhere you have implemented it to run? You could try Static Web Apps.

**Comment by PaulusTM** [comment]
It's only tested locally for the moment @jansche. Should I publish it?

**Comment by jansche** [comment]
Yes please. I trust you, and will add you to the Hall of Fame in an instant. But nothing beats the experience of real serverless when going from prod to live. =)
