### ISSUE TITLE
Can the Challenge(s) posting schedule be made available ahead of time ?

### ISSUE THREAD

**Issue by lohithgn** [microsoft/Seasons-of-Serverless#28]
Hi,

Thanks for the seasons of serverless. Love the azure functions and hence excited to participate in this.

Suggestion: Is it possible for you to put the dates on which the challenges will be posted ahead of time - May be a bulleted list in the readme. That suffices. That lets me put a reminder for myself to look into this repo on that particular date to check the new challenge?

Thoughts ?

Thanks.

**Comment by jansche** [comment]
Hi @lohithgn 
We're publishing every Monday trying to be updating the repo in the early morning hours of GMT/UTC. I'll make sure it finds its way into README.md. Thanks for letting us know this is helpful! =) 
Cheers
Jan
