### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 2 - TypeScript

### ISSUE THREAD

**Issue by lechnerc77** [microsoft/Seasons-of-Serverless#29]
Please provide the following information for your submission:

### What is your name? (First, Last)
Christian Lechner

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/lechnerc77/SeasonOfServerlessWeek2

### What Challenge is this for? (Challenge number between 1 and 7)
2

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
The language used is TypeScript. The classification works for ladoo, doughnuts and cake (when I say cake, I mean Apple pie :-))

I deviated a bit from the original task to provision the image via file upload, but this makes the call in Azure a bit cumbersome, which is the reason why this solution focuses on the URL-based provisioning of pictures. However, the code contains the relevant calls to read a file form the files system and the call of the Custom Vision API.

You cannot run the function locally, as the keys for the Custom Vision API are not pushed to this repository. They are stored in local.settings.json and the App Settings.  The API is provisioned on Azure at the endpoint https://seasonofserverlessweek2.azurewebsites.net/api/LovelyLadoosClassifier (No authentication needed - imho better tradeoff than publishing the keys and internal information of the custom vision API).

**Comment by jansche** [comment]
Hey @lechnerc77 
I tried to use an online service to pass a JSON body to the API. Unfortunately, I'm not very familiar with this stuff, so I failed and I couldn't make your solution work. Is there an easy way how I can test it? 
Cheers
Jan

**Comment by lechnerc77** [comment]
Hi @jansche,
sure. you have two options: 

Use the requests in the `demorequest.http` file in my repo (prerequiste: [REST Client Extension for VSCode](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)): 
![demorequests_http](https://user-images.githubusercontent.com/22294087/101144879-4682ed80-3619-11eb-8a8e-b244c4cc282f.png)

Alternatively you can use Postman to call the API
![Postman](https://user-images.githubusercontent.com/22294087/101145070-8c3fb600-3619-11eb-899f-df86d54bba04.png)
Here enter the URL for the request (`https://seasonofserverlessweek2.azurewebsites.net/api/LovelyLadoosClassifier`), go to the body tab, select raw and format JSON (as in the screenshot) and then enter e. g. 
```
{
    "url": "https://www.cookingclassy.com/wp-content/uploads/2014/01/krispy-kreme-copycat-recipe-edit+text..jpg"
}
```

**Comment by jansche** [comment]
Thank you, Christian!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
