### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 2 Custom Vision & .NET

### ISSUE THREAD

**Issue by marcduiker** [microsoft/Seasons-of-Serverless#30]
Please provide the following information for your submission:

### What is your name? (First, Last)
Marc Duiker

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/marcduiker/Seasons-of-Serverless/tree/main/src/challenge-2

### What Challenge is this for? (Challenge number between 1 and 7)
2

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
I've described my process in this Tweet thread: https://twitter.com/marcduiker/status/1333375872678637568

There is a Dutch snack (bitterballen) which look **very** similar. I added that as a second class.  Added golfballs as a third class 😂. Testing with (dark) brown ladoos is problematic due to the similarity.

Public endpoint for testing: 
https://seasonsofserverless-fa.azurewebsites.net/api/getprediction?img=https://livinglargetinylot.files.wordpress.com/2012/11/raagi-ladoos.jpg

**Comment by jlooper** [comment]
I usually burnen my tonguen with those bitterballen...smart test though!!

**Comment by jlooper** [comment]
Love it! works really well, even after I tried to trick it :)
