### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 2 - Python, Custom Vision and Static Website Storage Account

### ISSUE THREAD

**Issue by errbufferoverfl** [microsoft/Seasons-of-Serverless#31]
Please provide the following information for your submission:

### What is your name? (First, Last)
Rebecca Trapani

### Where is your GitHub Repo ?(Link to your challenge solution)
Detailed instructions: https://github.com/errbufferoverfl/violet-lobster
Python Solution: https://github.com/errbufferoverfl/violet-lobster/tree/main/week-02
Static Website: https://stglovelyladoostest.z8.web.core.windows.net/
Azure Function Endpoint: https://lovely-ladoos.azurewebsites.net/api/classify?img=https://upload.wikimedia.org/wikipedia/commons/0/04/New_York_Empire_Apples.jpg

### What Challenge is this for? (Challenge number between 1 and 7)
2

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

This solution used Food based Custom Vision with the training model based on:
* Ladoo
* Doughnut Holes
* Gulab Jamen
* Truffles

The model still struggles a lot with Apples, in particular Apples that are piled in a similar way to Ladoo images, so more training is needed.

The website is hosted on a [Static Website](https://stglovelyladoostest.z8.web.core.windows.net/) using a storage account, and the function just returns a JSON response so you can also navigate directly to the [Azure Function](https://lovely-ladoos.azurewebsites.net/api/classify?img=https://upload.wikimedia.org/wikipedia/commons/0/04/New_York_Empire_Apples.jpg).

I used this article from Microsoft to get started with [Python and Tensorflow](https://docs.microsoft.com/en-us/azure/azure-functions/functions-machine-learning-tensorflow?tabs=bash).

I didn't really document much of my process, but some of my training results were [tweeted about](https://twitter.com/errbufferoverfl/status/1333364941798002689).

This was a really fun and challenging problem but lots of fun to work on!

**Comment by jlooper** [comment]
Very cool! Sometimes I get an error, sometimes a result...wonder why?

**Comment by errbufferoverfl** [comment]
Something to investigate tonight! Thanks for the feedback! ♥

**Comment by jansche** [comment]
Hey @errbufferoverfl 
Thanks for your submission. It looks just awesome!

I had one image that caused the error that Jen might be referring to as well:
https://www.justataste.com/wp-content/uploads/2014/03/glazed-doughnut-holes-recipe.jpg

![Screenshot 2020-12-04 at 09 00 12](https://user-images.githubusercontent.com/22521588/101137688-80e78d00-360f-11eb-8937-24ab4bde2408.png)

Other than that, your solution looks just perfect.

Cheers
Jan

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
