### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 1 Solution - Python and Azure SQL serverless

### ISSUE THREAD

**Issue by dzsquared** [microsoft/Seasons-of-Serverless#32]
### What is your name? 
Drew Skwiers-Koballa

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/dzsquared/seasons-of-serverless-week1

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
Blog post: https://devblogs.microsoft.com/azure-sql/seasons-of-serverless-challenge-1-azure-functions-and-azure-sql-database-serverless/
A little late, but this solution utilizes an Azure Function written in Python to pull the recipe from an Azure SQL database (serverless tier).  I loved 25 days of serverless last year, but it was brutal and am very glad this is week by week. 🎉
Planning to post solutions on the Azure SQL dev blog each week by the end of the week.

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
