### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by Francescolatorre** [microsoft/Seasons-of-Serverless#33]
Please provide the following information for your submission:

### What is your name? (First, Last)
Francesco La Torre

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/Francescolatorre/serverless-challenge-turkey

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
I created it as a Azure Function using Javascript created following a TDD approach, providing a jest test with the solution.
It was quite easy and fun 💯.
I din't provide any user interface or such, the recipe is provided as json.

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
