### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge Two

### ISSUE THREAD

**Issue by stuartleaver** [microsoft/Seasons-of-Serverless#36]
Please provide the following information for your submission:

### What is your name? (First, Last)

Stuart Leaver

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/stuartleaver/seasons-of-serverless/tree/main/02-lovely-ladoos

### What Challenge is this for? (Challenge number between 1 and 7)

2

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

C#, an Azure Function, Custom Vision, Vue.js and a Static Web App. Types of images used were ladoos, doughnuts and strawberries.

Try it out at - https://www.lovelyladoos.cloud

**Comment by jansche** [comment]
You even registered a domain, @stuartleaver. Wow!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
