### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 02 - PowerShell

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/Seasons-of-Serverless#37]
Please provide the following information for your submission:

### What is your name? (First, Last)
Barbara Forbes

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/Ba4bes/SeasonsOfServerless/tree/main/C02-Lovely_Ladoos

### What Challenge is this for? (Challenge number between 1 and 7)

Challenge 2

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

I made the ascii art myself this time. It probably shows 😅.

The complete story of how it happened an how the function can be called is in the readme 😀

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
