### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by PaulusTM** [microsoft/Seasons-of-Serverless#39]
Please provide the following information for your submission:

### What is your name? (First, Last)

Daniel Paulus

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/PaulusTM/Seasons-of-Serverless/tree/main/src/challenge-2

### What Challenge is this for? (Challenge number between 1 and 7)

2

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

Build in Typescript. You need to send the url of an image to check with your request. See the examples in the `test.http` file for more details.

The AI is trained to recognize Ladoo, Dutch Bitterballen, chewing gum, tennis balls.

Application is deployed to an Azure Function App at: https://ladoo-paulustm.azurewebsites.net/api/ladoovalidator

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
