### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 1 solution

### ISSUE THREAD

**Issue by marcduiker** [microsoft/Seasons-of-Serverless#4]
Please provide the following information for your submission:

### What is your name? (First, Last)
Marc Duiker

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/marcduiker/Seasons-of-Serverless/tree/challenge-1/src/challenge-1

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

I've used C#, added a Recipe class where I do the calculations and formatting. I'm using a specific function route that contains the weight of the turkey. It also checks if the weight is positive. If not, it returns a BadRequest message (HTTP 400).

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
