### ISSUE TITLE
[CHALLENGE SUBMISSION] Week 3 .NET based Azure Function

### ISSUE THREAD

**Issue by marcduiker** [microsoft/Seasons-of-Serverless#41]
Please provide the following information for your submission:

### What is your name? (First, Last)

Marc Duiker

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/marcduiker/Seasons-of-Serverless/tree/main/src/challenge-3

### What Challenge is this for? (Challenge number between 1 and 7)

3

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

I based the calculation on the recipe linked in the challenge. I'm estimating that with the original recipe you can make 4 kebabs of +/- 12cm each, so 48 cm (0.48m) in total.

The function can be tested here: https://seasonsofserverless-fa.azurewebsites.net/api/recipe/kebab/0.45?code=O2wmYhSCd4NaTtMTrMbw3oHUSS/WPxLyoce74n7VmWexvEjI6rxt1w==

The response:
```json
{
    "recipeSource":"https://www.thespruceeats.com/adana-kebab-4164647",
    "nrOfServings":"Number of servings: 4.",
    "length":"Total length of the kebab: 0.48 meter.",
    "lamb":"Lamb meat: 0.45 kg.",
    "onion":"Onions: 1 pieces.",
    "garlic":"Garlic cloves: 4 pieces.",
    "cumin":"Cumin: 1.5 teaspoons.",
    "sumac":"Sumac: 1.5 teaspoons.",
    "salt":"Salt: 0.5 teaspoons.",
    "blackPepper":"Black pepper: 0.25 teaspoons.",
    "pepperFlakes":"Red pepper flakes: 0.25 teaspoons.",
    "water":"Ice cold water: 2 tablespoons."
}
```

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
