### ISSUE TITLE
[CHALLENGE SUBMISSION] Week 3 Azure Function in TypeScript

### ISSUE THREAD

**Issue by lechnerc77** [microsoft/Seasons-of-Serverless#43]
Please provide the following information for your submission:

### What is your name? (First, Last)

Christian Lechner

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/lechnerc77/SeasonOfServerlessWeek3

### What Challenge is this for? (Challenge number between 1 and 7)

3

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

* The calculation of the serving is based on the [recipe](https://www.thespruceeats.com/adana-kebab-4164647) provided in the challenge description. The base unit is 453 grams of ground lamb which delivers 4 servings
* The length of the kebab is calculated based on the following assumptions:
  * The average density of ground lamb is 0.96 g/ml (comparable to beef). With this information we can calculate the volume of the lamb (we neglect the volume added by the other ingredients)
  * We assume the basic geometric form of kebab is a cylinder so the volume is  V = r² * h * 𝜋. Consequently we can calculate the length as a variable of the radius.
  * We calculate the length of the kebab in cm for 3 possible diameters (3, 6 and 9 cm)
* The evaluation of the recipe is also based on the values given [here](https://www.thespruceeats.com/adana-kebab-4164647)

You can run the functions locally via `npm run start`. Several HTTP calls are available in the file `requests.http` (required: [REST Client extension in VSCode](https://marketplace.visualstudio.com/items?itemName=humao.rest-client))

**Comment by jlooper** [comment]
Loving this detailed and flexible computation!!

**Comment by jansche** [comment]
Hi @lechnerc77 
I'm intrigued by your math volume approach. <3 
I ran your solution on my machine, but the environment kept crashing. 
![image](https://user-images.githubusercontent.com/22521588/101485401-67ba4580-395b-11eb-8788-703a62df34ec.png)
Would you be able to publish an endpoint? Should be easy to do that with Azure Static Web Apps. Here's the Quickstart guide if you want: https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript

**Comment by jlooper** [comment]
ah it looks like your Node version isn't compatible with the function version. let me try

**Comment by lechnerc77** [comment]
You must use node12 for local execution as the Azure Functions runtime only supports the LTS releases of node. You are using node 13. 

I just deployed it to Azure. Here are some sample calls:
* https://seasonsofserverlessweek3.azurewebsites.net/api/TheLongestKebab?weightingrams=453
* https://seasonsofserverlessweek3.azurewebsites.net/api/TheLongestKebab?weightingrams=1000
* https://seasonsofserverlessweek3.azurewebsites.net/api/TheLongestKebab?weightingrams=5000

**Comment by jlooper** [comment]
I got it running, looks great. Love the diameter calculations!

{
  "🍽 - Number of servings ": 4,
  "📏 - Length of Kebap (in cm)": [
    {
      "Diameter 3 cm": "58.9"
    },
    {
      "Diameter 6 cm": "14.7"
    },
    {
      "Diameter 9 cm": "6.5"
    }
  ],
  "📜 - Ingredients": [
    "0.9 small onions (minced)",
    "3.5 cloves garlic (minced)",
    "1.3 teaspoons ground cumin (divided)",
    "1.3 teaspoons ground sumac (divided)",
    "0.4 teaspoon salt",
    "0.22 teaspoon ground black pepper",
    "0.22 teaspoon red pepper flakes",
    "2 tablespoons water"
  ]
}

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
