### ISSUE TITLE
[CHALLENGE SUBMISSION] Week 3 - Python 3.8

### ISSUE THREAD

**Issue by errbufferoverfl** [microsoft/Seasons-of-Serverless#44]
Please provide the following information for your submission:

### What is your name? (First, Last)
Rebecca Trapani

### Where is your GitHub Repo ?(Link to your challenge solution)
Detailed instructions: https://github.com/errbufferoverfl/violet-lobster
Python Solution: https://github.com/errbufferoverfl/violet-lobster/tree/main/week-03
Azure Function Endpoint:

- Flexitarian Recipe: https://longest-kebab.azurewebsites.net/api/tartmak?type=flexitarian&weight=200
- Vegan Recipe: https://longest-kebab.azurewebsites.net/api/tartmak?type=vegan&weight=200

### What Challenge is this for? (Challenge number between 1 and 7)
3

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
I went back to basics this week so I could focus on adding in multiple options :) works using kilograms and bases it's measurement on a 12cm x 4 kebabs based on the image. The vegan recipe was based on the same ratio.

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
