### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge03 - PowerShell

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/Seasons-of-Serverless#45]
Please provide the following information for your submission:

### What is your name? (First, Last)

Barbara Forbes

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/Ba4bes/SeasonsOfServerless/tree/main/C03-The_Longest_Kebab

### What Challenge is this for? (Challenge number between 1 and 7)

3

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
The challenge was mostly finding all information and then making the solution as flexible as possible!
It can calculate from the meat weight, the amount of people that needs to be fed or the total length needed.

And my Ascii art extually expands if the kebab gets longer! :-D

![image](https://user-images.githubusercontent.com/43912004/101672570-53a73e80-3a56-11eb-9c8b-411db48fbe09.png)

More info in the [readme](https://github.com/Ba4bes/SeasonsOfServerless/tree/main/C03-The_Longest_Kebab)

**Comment by jlooper** [comment]
wow it's sooo good!

**Comment by jansche** [comment]
Loving it. The ascii art and the functionality is gorgeous!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
