### ISSUE TITLE
[CHALLENGE SUBMISSION] Week 3 - C#

### ISSUE THREAD

**Issue by josercadena** [microsoft/Seasons-of-Serverless#48]
Please provide the following information for your submission:

### What is your name? (First, Last)
Jose R. Cadena

### Where is your GitHub Repo? 
https://github.com/josercadena/seasons-of-serverless-week-3

### What Challenge is this for? 
3

### (Optional) Anything else we should know? 
Solved using C# - I assumed a serving with a length of 10 cm (including all ingredients) and consistent distribution of ingredients :) More details in my repo

You can play with it [here](https://kebab-example.azurewebsites.net/api/KebabExample?meatAmount=12). I will delete the Azure Functions after the end of the week 🌚

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
