### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge Three (Typescript & Angular)

### ISSUE THREAD

**Issue by stuartleaver** [microsoft/Seasons-of-Serverless#49]
Please provide the following information for your submission:

### What is your name? (First, Last)

Stuart Leaver

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/stuartleaver/seasons-of-serverless/tree/main/03-the-longest-kebab

### What Challenge is this for? (Challenge number between 1 and 7)

3

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

Typescript. No C# is sight.

Why not take the opportunity to use a different language from normal. So for this challenge, I went for writing the Azure Function in Typescript. There is then the UI in Angular, and as before, hosted using a Static Web Site.

Try it out at - https://www.thelongestkebab.cloud

I think I've committed to buying domain names now 🤣 

The length calculation came from reading [Turkish Ground Lamb Kebabs (Adana Kebabs)](https://www.saveur.com/turkish-ground-lamb-kebabs-recipe/). Taking into account the amount of meat in that recipe, the number it servers, and the length of the skewers suggested, it came to about 156g equalled 25.4cm. It may only be an estimation, but these challenges are all about having fun.

**Comment by jlooper** [comment]
Wow, it's amazing. Somehow I feel like you could create a tutorial about this series of epic recipes....

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉

**Comment by stuartleaver** [comment]
> Wow, it's amazing. Somehow I feel like you could create a tutorial about this series of epic recipes....

@jlooper I did have that thought as well and that it may be good as a "summary" at the end of the series. I've got some time off work over the festive period, so I'll see what happens.
