### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 4 PowerShell

### ISSUE THREAD

**Issue by EwertonJordao** [microsoft/Seasons-of-Serverless#51]
Please provide the following information for your submission:

### What is your name? (First, Last)

Ewerton Jordão

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/EwertonJordao/bbqbrazil_seasonserverless4

### What Challenge is this for? (Challenge number between 1 and 7)
4
### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

I try to use some resources uncommon in PowerShell, class definitions and methods for create that solution. Use PowerShell always 😎🤘

**Comment by jansche** [comment]
Hi @EwertonJordao,
thanks a lot for your submission! Would you provide a public endpoint, e.g. through Azure Static Web Apps, so we can see your solution in action?
A handy guide to creating a Static Web App (or just the Function) can be found here: 
[](https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript) and 
[](https://github.com/GeekTrainer/aswa-student-starter-kit).

**Comment by EwertonJordao** [comment]
Hi @jansche,

Of course, public endpoint: https://seasonsbbqbr.azurewebsites.net/api/bbqbrazil?code=BIzFkmYeg4GDrU0D2DErpMXMGNTHJ/3maRS26cz9EXYY7g3n/up1ug==

Sample request: 

```powershell
$body =((@{Name = "Jordao"; QtdPeople = 5 }, @{Name = "Sanchez"; QtdPeople = 6 }) | ConvertTo-Json)
Invoke-RestMethod -Uri  "https://seasonsbbqbr.azurewebsites.net/api/bbqbrazil?code=BIzFkmYeg4GDrU0D2DErpMXMGNTHJ/3maRS26cz9EXYY7g3n/up1ug==" `
    -Body  $body `
    -ContentType "application/json" `
    -headers @{Budget = 1500 } `
    -Method Get
```

**Comment by jansche** [comment]
I think your API is not online anymore, but looking at your code this all seems reasonable. Make sure to check out the other solutions as well. 👍

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
