### ISSUE TITLE
[CHALLENGE SUBMISSION] Week 4 Azure Function in JavaScript

### ISSUE THREAD

**Issue by lechnerc77** [microsoft/Seasons-of-Serverless#52]
Please provide the following information for your submission:

### What is your name? (First, Last)
Christian Lechner

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/lechnerc77/SeasonOfServerlessWeek4

### What Challenge is this for? (Challenge number between 1 and 7)
4

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
I am not quite sure if I understood what the Excel should have told me :-)
In addition it is quite some time ago that I worked on mathematical optimization problems (a loonnngggg time ago) 
So I tried to tackle the optimization problem by a linear optimization approach that made some modelling as well as some assumptions necessary to apply that method. For the details I refer to the the description in my [repository](https://github.com/lechnerc77/SeasonOfServerlessWeek4/blob/main/README.md). 

You can execute the function locally via `func start`. Some sample calls are available in the file `requests.http`.

**Comment by jlooper** [comment]
I think you got it! The idea is having the most value for your BBQ - discovering what you can serve and what you should cut back on to support the greatest number of guests for the least amount of money. I think you did that, well done!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
