### ISSUE TITLE
[CHALLENGE SUBMISSION] Week 04 - Python!

### ISSUE THREAD

**Issue by errbufferoverfl** [microsoft/Seasons-of-Serverless#53]
Please provide the following information for your submission:

### What is your name? (First, Last)
Rebecca Trapani

### Where is your GitHub Repo ?(Link to your challenge solution)

Detailed instructions: https://github.com/errbufferoverfl/violet-lobster
Python Solution: https://github.com/errbufferoverfl/violet-lobster/tree/main/week-04
Azure Function Endpoint: https://big-bbq.azurewebsites.net/api/calcbudget?budget=99999

### What Challenge is this for? (Challenge number between 1 and 7)
4

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

I originally tried to use linear programming to try and find the optimal amount of each food but I didn't have enough constraints so the program was just really keen about buying halloumi.

In the end I ended up defining an estimated amount people would eat, in this case 700g and then a percentage of what people would eat, for example 25% fillet, 5% potato, 5% mushroom etc. based on this I could determine how much each person would want to eat and the cost per person. From there I could then divide my budget by that cost per person and work out how much I would spend!

I spent a fair bit of time working on the linear programming so when that didn't work I ended up just focusing on providing the answer we originally wanted i.e how many people can we serve based on our budget but also added in the cost per person, and amount of change left.

It also provides you with a helpful shopping list so you buy the 🎇 perfect 🎇 amount! I might use this to work out what I need to buy for Christmas day 🤔

**Comment by jansche** [comment]
I love how the list is ready to be printed and off we go for grocery shopping. Thank you @errbufferoverfl!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
