### ISSUE TITLE
Week 4 challenge description and unclear excel file

### ISSUE THREAD

**Issue by marcduiker** [microsoft/Seasons-of-Serverless#54]
Hi team!

I've looked at the challenge for week 4 and although the description in markdown is ok, the excel file that is linked is a bit unclear. I can imagine we'll lose some engagement due to this unclarity. Perhaps the text in the markdown can be changed to describe that the linked excel file is just an example how people deal with planning for a big BBQ and not use it as the basis for their solution. I'll submit a PR with an alternative text, OK?

**Comment by jlooper** [comment]
thanks!!!
