### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge Four (C# and Angular)

### ISSUE THREAD

**Issue by stuartleaver** [microsoft/Seasons-of-Serverless#56]
Please provide the following information for your submission:

### What is your name? (First, Last)

Stuart Leaver

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/stuartleaver/seasons-of-serverless/tree/main/04-a-big-barbecue

### What Challenge is this for? (Challenge number between 1 and 7)

4

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

C# (Azure Function) and Angular.

The solution contains an Angular frontend to allow users to input the details of their barbecue, and an Azure Function as the backend to calculate the costs and how the spend compares to the budget.

The BBQ organiser can input the following details:
* Their name
* Number of guests
* Budget
* The items for their barbeque, cost per kg/pcs and the quantity

Some example prices have been pre-filled.

Using the spreadsheet as a guide and a bit of artistic license, the Azure Function will then calculate the following:
* Total cost of the items
* Cost per guest
* Over or under budget

These details are then displayed back to the user, along with the list of items they need.

If the cost of a barbecue item is £0 or above and the quality is greater than 0, then the item will be included in the costs.

**Comment by jlooper** [comment]
super duper!

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
