### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 04: PowerShell

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/Seasons-of-Serverless#58]
Please provide the following information for your submission:

### What is your name? (First, Last)
Barbara Forbes

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/Ba4bes/SeasonsOfServerless/tree/main/C04-A_Big_Barbecue

### What Challenge is this for? (Challenge number between 1 and 7)

4

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

I got to use CosmosDB again ❤. 
Please read the Readme, I made an explanation of everything I did and the different options in the function 😀

**Comment by jlooper** [comment]
thank you for this submission!
