### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 5 - Azure Logic Apps

### ISSUE THREAD

**Issue by lechnerc77** [microsoft/Seasons-of-Serverless#59]
Please provide the following information for your submission:

### What is your name? (First, Last)

Christian Lechner

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/lechnerc77/SeasonsOfServerlessWeek5

### What Challenge is this for? (Challenge number between 1 and 7)

5

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

This week the solution is provided in a low-code manner i.e. via Azure Logic Apps. However as I decided to guide the cook via emails, I will not publish the endpoint to avoid unnecessary emails triggered.  Nevertheless the code view is available in the repository as an extensive walk-through the steps of the Logic App flow. So enjoy and  잘 먹겠습니다

**Comment by jlooper** [comment]
thank you for this submission!
