### ISSUE TITLE
[CHALLENGE SUBMISSION] Week1 (Turkey) - Horgix - Python+SLS

### ISSUE THREAD

**Issue by Horgix** [microsoft/Seasons-of-Serverless#6]
Please provide the following information for your submission:

### What is your name? (First, Last)

Alexis Horgix Chotard

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/Horgix/seasons-of-serverless/tree/master/w1-turkey-recipe

### What Challenge is this for? (Challenge number between 1 and 7)

1

### Demo

Live at <https://sls-neur-dev-horgix-turkey-recipe.azurewebsites.net/api/recipe?turkeyWeight=10>
```
curl https://sls-neur-dev-horgix-turkey-recipe.azurewebsites.net/api/recipe?turkeyWeight=10 
```

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

This submission is done using **Python 3.8**. It is deployed as an **Azure Function** using the [**Serverless Framework**](https://www.serverless.com/framework/docs/providers/azure/guide/intro/). This is a dead simple solution, done in a rush (no tests, CI, etc). The recipe returned is in JSON.

**Challenges** faced: no documentation on Serverless Framework Azure provider regarding using already-existing Azure resource group. Found it in the code. I also could not find a way to remove the ` sls-neur-dev-` prefix added by Serverless Framework (but didn't take that much time to find a solution to be honest)

**Cool** stuff: appreciate the `mimetype` in the `azure-functions` SDK' `HttpResponse`! Usually I have to define the `Content-Type` header manually when working with other FaaS providers.

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
