### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge 5 (Azure Functions, Durable Functions, SignalR, SendGrid)

### ISSUE THREAD

**Issue by stuartleaver** [microsoft/Seasons-of-Serverless#60]
Please provide the following information for your submission:

### What is your name? (First, Last)

Stuart Leaver

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/stuartleaver/seasons-of-serverless/tree/main/05-tteok-guk-for-the-new-year

### What Challenge is this for? (Challenge number between 1 and 7)

5

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

This solution makes use of a Blazor WASM UI, Azure Functions, SignalR, and SendGrid. For the Functions, Durable Functions are used to keep track of the 'waiting' periods, and then SignalR is used to broadcast 'completed' messages back to the UI. SendGrid is also used to send reminder emails.

The waits are actually 30, 8, and then 30 minutes, but the screenshots should show a finished run through.

**Comment by jlooper** [comment]
thank you for this submission!
