### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 05: Logic Apps

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/Seasons-of-Serverless#61]
Please provide the following information for your submission:

### What is your name? (First, Last)

Barbara Forbes

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/Ba4bes/SeasonsOfServerless/tree/main/C05-Tteok-guk_for_The_New_Year

### What Challenge is this for? (Challenge number between 1 and 7)

5

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

For this challenge I combined Logic Apps and Teams! This makes it a bit harder to share the solution, especially since it was created with the designer. I added the code to the repository and made some gifs of the process in Teams, to give you a bit of the experience :)

**Comment by jlooper** [comment]
thank you for this submission!
