### ISSUE TITLE
[CHALLENGE SUBMISSION] - Power Automate/Microsoft Flow

### ISSUE THREAD

**Issue by LocksleyLK** [microsoft/Seasons-of-Serverless#62]
Please provide the following information for your submission:

### What is your name? (First, Last)
Locksley Kolakowski

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/LocksleyLK/seasons-of-serverless/tree/master/Challenge-5

### What Challenge is this for? (Challenge number between 1 and 7)
5

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
My solution utilizes Microsoft Flow in Power Automate. According to my research, Microsoft Flow runs on top of Azure Logic Apps 😃. 

In my GitHub Repo, I have provided steps on how to recreate my solution and provided some images/gifs demonstrating how it works.

If you would like to test it yourself, I could share my solution with you in Power Automate via email!

**Comment by jlooper** [comment]
thank you for this submission!
