### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 6 - Azure Functions and Durable Entities in TypeScript

### ISSUE THREAD

**Issue by lechnerc77** [microsoft/Seasons-of-Serverless#63]
Please provide the following information for your submission:

### What is your name? (First, Last)

Christian Lechner

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/lechnerc77/SeasonOfServerlessWeek6

### What Challenge is this for? (Challenge number between 1 and 7)

6

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

This is a solution for the challenge of week 6 using TypeScript. The solution is a combination of Azure Functions 8serving as `durableClients` and Azure Durable Entities for storing the state:

* Azure Durable Entity `ChocolateBoxEntity`: This entity stores the available amount of chocolate per chocolate type. It constraints the maximum amount of chocolate per type to two pieces.
* Azure Durable Entity `ReservationEntity`: This entity stores the reservation of chocolate per person.
* Azure Function `ReserveChocolate`: This functions offer a `POST` endpoint for reserving chocolate for a person. You must provide the input parameters via JSON e. g.
  
  ```JSON
  {
    "name": "Christian",
    "type": "Rocher Noir"
  }  
  ```

* Azure Function `ChocolateReservationStatus`: This functions offer an endpoint available to `GET` and `DELETE`. It accepts the query parameter `name`.
  * `GET` fetches the current status of a reservation for the person handed over via the query parameter
  * `DELETE` removes the reservation for the person handed over via the query parameter.

The details and "story line" of the solution are described in the repo in the section [Internal Design](https://github.com/lechnerc77/SeasonOfServerlessWeek6/blob/main/README.md#internal-design)

**Comment by jlooper** [comment]
thank you for this submission!
