### ISSUE TITLE
[CHALLENGE SUBMISSION] :PowerShell functions and CosmosDB

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/Seasons-of-Serverless#64]
Please provide the following information for your submission:

### What is your name? (First, Last)

Barbara Forbes

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/Ba4bes/SeasonsOfServerless/tree/main/C06-The_Magic_Chocolate_Box

### What Challenge is this for? (Challenge number between 1 and 7)

6

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

>(all info and screenshots of the results can be found in the Readme!)

Unfortunately, no support for durable entities and PowerShell ☹. So I made it all work with a CosmosDB 😄.
The chocolates are stored in a database. The function gives the following functionality:

#### Add chocolate to the database

```PowerShell
$Body = @{
    Name          = "Cookie bonbon"
    ChocolateType = "white"
    Filling       = "cookie crumble"
    ClaimedBy     = "false"
}
Invoke-RestMethod https://4besc06.azurewebsites.net/api/Add-Chocolate -body ($Body | ConvertTo-Json)
```

#### Get available chocolate

```PowerShell
Invoke-RestMethod https://4besc06.azurewebsites.net/api/Get-UnclaimedChocolate
```

#### Claim a piece of chocolate

```PowerShell
$Body = @{
    "MyName" = "Barbara"
    "ChocName" = "pure coconut"
}

Invoke-RestMethod https://4besc06.azurewebsites.net/api/Claim-Chocolate -body ($Body | ConvertTo-Json)
```

(this is also where you can get the ascii art/text art!)

![image](https://user-images.githubusercontent.com/43912004/103352890-bf098c80-4aa7-11eb-9f0c-0ae3585400f9.png)

[source for ascii art](https://textart.sh/topic/chocolate)

### Get the results

All unclaimed chocolate will be distributed randomly

```PowerShell
$Family = @(
    "Bit"
    "Fred"
    "Barbara"
)

Invoke-RestMethod https://4besc06.azurewebsites.net/api/Get-Chocdistribution -body ($Body | ConvertTo-Json)
```

**Comment by jlooper** [comment]
Love this!! thank you for this submission!
