### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge Six (Durable Entities with C#, Vue.js)

### ISSUE THREAD

**Issue by stuartleaver** [microsoft/Seasons-of-Serverless#65]
Please provide the following information for your submission:

### What is your name? (First, Last)

Stuart Leaver

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/stuartleaver/seasons-of-serverless/tree/main/06-the-magic-chocolate-box

### What Challenge is this for? (Challenge number between 1 and 7)

6

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

The solution makes use of Azure Functions written in C#, Vue.js. For the Functions, Durable Entities are used to maintain the state of different families. This state being the chocolate box they selected and the reservations their family members have made.

As the functions for the Durable Entities are hosted in a Function app, it is possible to try them out separate from the UI. There are details on the endpoints in the [README.md](https://github.com/stuartleaver/seasons-of-serverless/blob/main/06-the-magic-chocolate-box/README.md) file. There is also an example 'family' in [SHEPPARDEXAMPLE.md](https://github.com/stuartleaver/seasons-of-serverless/blob/main/06-the-magic-chocolate-box/SHEPPARDEXAMPLE.md).

The endpoint where they can be tested is https://magicchocolatebox.azurewebsites.net

**Comment by jlooper** [comment]
thank you for this submission!
