### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 6 - Durable Entities in C#

### ISSUE THREAD

**Issue by marcduiker** [microsoft/Seasons-of-Serverless#66]
Please provide the following information for your submission:

### What is your name? (First, Last)

Marc Duiker

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/marcduiker/Seasons-of-Serverless/tree/challenge-6/src/challenge-6

### What Challenge is this for? (Challenge number between 1 and 7)

6

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

I've used Durable Functions/Entities with C#. I've created `ChocolateBox` model with a list for the available chocolates and a dictionary for the reserved chocolates (person name is key, chocolate name is value). The `ChocolateBox` has methods to add/remove chocolates and to reserve/unreserve chocolates. A person can only have one chocolate reserved. Reserving another chocolate results in undoing the previous reservation by that person. 

The function can be tested live:

#### Retrieving the list of available and reserved chocolates
```
GET https://seasonsofserverless-fa.azurewebsites.net/api/list?code=zQQ9wlSiGDF/MPe7gKQMq5f05w8pcYqDKp10if3bcxI2c3QW9pMAFg==
```

Response example:
```
{
  "available": [
    "supreme cafe",
    "nougat",
    "nougatine",
    "edelweiss",
    "maya",
    "vinay",
    "brazil",
    "fondinette",
    "truffe",
    "supreme caramel"
  ],
  "reserved": {
    "Marc": "chardon blue"
  }
}
```

#### Making a chocolate reservation

Requires a person name.
The name of the chocolate is optional. If it is left empty a random chocolate will be reserved.
This is an async call so this won't return the list with the available/reserved chocolates. Use the `list` call to retrieve the results.

```
POST https://seasonsofserverless-fa.azurewebsites.net/api/reservation/{PERSON_NAME}/{CHOCOLATE_NAME}?code=1shzqyQtbIotdsoOP/LbYBWjgyEtxFEyhbXkMDNZpxHUkj7DkKJvGA==
```

#### Undoing the reservation:

Requires a person name who has made a reservation.
This is an async call so this won't return the list with the available/reserved chocolates. Use the `list` call to retrieve the results.
```
DELETE https://seasonsofserverless-fa.azurewebsites.net/api/reservation/{PERSON_NAME}?code=1shzqyQtbIotdsoOP/LbYBWjgyEtxFEyhbXkMDNZpxHUkj7DkKJvGA==
```

**Comment by jlooper** [comment]
Love it!!
