### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge 6 - JavaScript

### ISSUE THREAD

**Issue by LocksleyLK** [microsoft/Seasons-of-Serverless#67]
### What is your name? (First, Last)
Locksley Kolakowski

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/LocksleyLK/seasons-of-serverless/tree/master/challenge-6 

### What Challenge is this for? (Challenge number between 1 and 7)
6

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
I used JavaScript for my challenge of solution.

You can test it out with the following links. I currently have it assigning an Espresso Shot Chocolate to myself, but you can edit the URL to assign chocolates to more people:
1. [View chocolate box](https://choosechocolates.azurewebsites.net/api/GetReservations)
2. [Make a reservation](https://choosechocolates.azurewebsites.net/api/ReserveChocolate?name=Locksley&item=Espresso%20Shot)
3. [View updated chocolate box and reservations](https://choosechocolates.azurewebsites.net/api/GetReservations)
4. [Clear chocolate box](https://choosechocolates.azurewebsites.net/api/ReserveChocolate?reset=true)

**Comment by jlooper** [comment]
nice! Thank you!
