### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 7 - Azure Functions in Go on SAP Cloud Platform Kyma :-)

### ISSUE THREAD

**Issue by lechnerc77** [microsoft/Seasons-of-Serverless#69]
Please provide the following information for your submission:

### What is your name? (First, Last)

Christian Lechner

### Where is your GitHub Repo ?(Link to your challenge solution)

https://github.com/lechnerc77/SeasonOfServerlessWeek7

### What Challenge is this for? (Challenge number between 1 and 7)

7

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.

The challenge of week 7 was not 100% clear to me and also changed a bit in between. As a consequence this solution focuses a more on what is possible with Azure Functions and not too much on the specifics of the challenge. In addition I did not want to create a Twilio account.

The solution provides an http endpoint `api/recipe/`:

* specifying the country `api/recipe/nigeria` or `api/recipe/kenya` will give you a list of dishes for Kenya and Nigeria including links to their recipes
* adding a query parameter with the name of the dish will directly hand back the dish and link to recipe if one is found. An example call would be `api/recipe/kenya?recipename=Karanga`

Now the playground part; 
* Internally the solution is based on Azure Functions custom handler making use of Go. I have build a simple serverthat has a handler for two routes.
* Depending on the provisioning of the query parameter `recipename` either a specific recipe link is returned if found in the hard coded values or the complete list of available recipe links is returned for the country specified in the path.
* Why not deploy the solution to ... let us say SAP Cloud Platform [Kyma](https://kyma-project.io/) that represents a Kubernetes-based opinionated runtime. 
* So we build the Docker container (and learned that the func-CLI has a bug for custom handlers when it comes to Docker files) for our Azure Function in Go 
* Deploy the image to Kyma including the corresponding API Rule. 

Examples how to call are given in the repository i. e. in the file [`request.http`](https://github.com/lechnerc77/SeasonOfServerlessWeek7/blob/main/request.http)

**Comment by jlooper** [comment]
This is kind of interesting, can you tell me why the Kyma decision?

**Comment by lechnerc77** [comment]
I am working in the area/word between SAP and Microsoft, trying to bridge the gap (official term is SAP Embrace). I really like the Kyma project per se and the mindset behind it delivering an opinionated Kubernetes Stack targeting the application extension. So I wanted to show one option how you can bring the two worlds together. Unfortunately the managed Kyma on SAP Cloud Platform does not allow to deploy custom resources like KEDA, so the scaling wouldn't be optimal in a real-world scenario.
