### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge 1 via Power App

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/Seasons-of-Serverless#8]
Please provide the following information for your submission:

### What is your name? (First, Last)
Brandon H

### Where is your GitHub Repo ?(Link to your challenge solution)
https://github.com/brandonh-msft/2020-seasons-of-serverless/tree/main/challenge-1

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
Solved via a Power App:
![](https://github.com/brandonh-msft/2020-seasons-of-serverless/raw/main/challenge-1/demo.gif)

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
