### ISSUE TITLE
[CHALLENGE SUBMISSION] The Perfect Turkey: python with Azure Functions Core Tools

### ISSUE THREAD

**Issue by ramanaditya** [microsoft/Seasons-of-Serverless#9]
Please provide the following information for your submission:

### What is your name? (First, Last)
Aditya Raman

### Where is your GitHub Repo? (Link to your challenge solution)
https://github.com/ramanaditya/Seasons-of-Serverless-2020-Solutions/tree/main/The-Perfect-Turkey

### What Challenge is this for? (Challenge number between 1 and 7)
1

### (Optional) Anything else we should know? e.g., language used, location, blog post, tell us how you solved this solution, including any challenges you faced solving it.
- language used: python3.8
- location: Bangalore, India

I used Azure Functions Core Tools to create the "Http Trigger" template and then edit the template to modify the logics to get Turkey brine. And also used Azure CLI to deploy the Function App.

**Comment by jansche** [comment]
From all of us at Developer Relations at Microsoft, thank you for participating in #SeasonsOfServerless and submitting a solution!

Wherever you are, stay safe and take care. 

Feel free to share your solution on Twitter with the tag [#SeasonsOfServerless](https://twitter.com/hashtag/SeasonsOfServerless).

**Comment by jansche** [comment]
Thanks for your awesome submission! 

 🎉 We've now added you and your solution to the [Hall of Fame](https://github.com/microsoft/Seasons-of-Serverless/blob/main/CONTRIBUTORS.md). 🎉
